function [ECG] = importECGbioharness(filename)

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/labodance/Documents/DataAnalysis/transfering_files_labodanse_3/2015_05_12_14_15/Bioharness/Day1/476/2015_05_12-17_55_51/2015_05_12-17_55_51_ECG.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/06/22 16:33:54

%% Initialize variables.
%filename = '/Users/labodance/Documents/DataAnalysis/transfering_files_labodanse_3/2015_05_12_14_15/Bioharness/Day1/476/2015_05_12-17_55_51/2015_05_12-17_55_51_ECG.csv';
delimiter = ','; %-- ALTERNATE2

%% Format string for each line of text:
%   column1: text (%s)
%	column2: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%[^\n\r]';  % -- ALTERNATE2
%formatSpec = '%10s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
%dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN, 'ReturnOnError', false); 
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'WhiteSpace', '', 'EmptyValue' ,NaN, 'ReturnOnError', false); % -- ALTERNATE2

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
ECG = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;